const bodyParser = require("body-parser");
const express = require("express");
const Router = require("./Routes/router");
const cors = require("cors");
require("dotenv").config();
const app = express();
app.use(express.json());
app.use(cors());
app.use(bodyParser.urlencoded({ extended: true }));
Router(app);
app.listen(process.env.PORT, () => console.log("sever is running..."));
